#!/usr/bin/env bash
set -euo pipefail

CHANNEL_ID="feishu-enhanced"
CONFIG_FILE="${HOME}/.openclaw/openclaw.json"
PERSIST_ZSHRC=1

ACCOUNTS=(
  "task-hub"
  "market-research"
  "data-analysis"
  "ad-ops"
  "logistics-customs"
  "finance-manager"
  "copy-editor"
)

usage() {
  cat <<'EOF'
Usage:
  bash scripts/setup-feishu-per-agent-interactive.sh \
    [--channel feishu-enhanced|feishu] \
    [--config ~/.openclaw/openclaw.json] \
    [--no-persist-zshrc]

What it does:
  1) Runs setup-feishu-per-agent.sh (accounts + bindings + backup)
  2) Prompts for 7x App ID/App Secret
  3) Writes ~/.openclaw/openclaw-feishu-agent-env.sh
  4) Optionally injects source line into ~/.zshrc (idempotent)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --channel)
      CHANNEL_ID="$2"
      shift 2
      ;;
    --config)
      CONFIG_FILE="$2"
      shift 2
      ;;
    --no-persist-zshrc)
      PERSIST_ZSHRC=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[error] Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "[error] Config not found: $CONFIG_FILE" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SETUP_SCRIPT="$SCRIPT_DIR/setup-feishu-per-agent.sh"
ENV_FILE="${HOME}/.openclaw/openclaw-feishu-agent-env.sh"
ZSHRC_FILE="${HOME}/.zshrc"
START_MARK="# >>> OPENCLAW_FEISHU_AGENT_ENV >>>"
END_MARK="# <<< OPENCLAW_FEISHU_AGENT_ENV <<<"

if [[ ! -f "$SETUP_SCRIPT" ]]; then
  echo "[error] Missing setup script: $SETUP_SCRIPT" >&2
  exit 1
fi

to_env_prefix() {
  local account_id="$1"
  local upper
  upper="$(printf '%s' "$account_id" | tr '[:lower:]' '[:upper:]')"
  printf '%s' "FEISHU_${upper//-/_}"
}

quote_sh() {
  # single-quote safe
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\"'\"'/g")"
}

remove_managed_block() {
  local file="$1"
  local tmp
  tmp="$(mktemp)"
  if [[ -f "$file" ]]; then
    awk -v start="$START_MARK" -v end="$END_MARK" '
      $0 == start { skip=1; next }
      $0 == end { skip=0; next }
      !skip { print }
    ' "$file" > "$tmp"
  else
    : > "$tmp"
  fi
  mv "$tmp" "$file"
}

echo "[step] writing channel accounts + bindings..."
bash "$SETUP_SCRIPT" --channel "$CHANNEL_ID" --config "$CONFIG_FILE"

mkdir -p "$(dirname "$ENV_FILE")"

declare -A APP_IDS
declare -A APP_SECRETS

echo
echo "[input] Please enter Feishu App credentials for each agent account."
echo "        accountId -> agentId mapping is 1:1."
echo

for account in "${ACCOUNTS[@]}"; do
  prefix="$(to_env_prefix "$account")"

  read -r -p "[$account] ${prefix}_APP_ID: " app_id
  while [[ -z "${app_id// }" ]]; do
    read -r -p "[$account] ${prefix}_APP_ID (required): " app_id
  done

  read -r -s -p "[$account] ${prefix}_APP_SECRET: " app_secret
  echo
  while [[ -z "${app_secret// }" ]]; do
    read -r -s -p "[$account] ${prefix}_APP_SECRET (required): " app_secret
    echo
  done

  APP_IDS["$prefix"]="$app_id"
  APP_SECRETS["$prefix"]="$app_secret"
done

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by setup-feishu-per-agent-interactive.sh"
  echo "# Generated at: $(date '+%Y-%m-%d %H:%M:%S %z')"
  echo
  for account in "${ACCOUNTS[@]}"; do
    prefix="$(to_env_prefix "$account")"
    printf 'export %s_APP_ID=%s\n' "$prefix" "$(quote_sh "${APP_IDS[$prefix]}")"
    printf 'export %s_APP_SECRET=%s\n' "$prefix" "$(quote_sh "${APP_SECRETS[$prefix]}")"
    echo
  done
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "[ok] wrote env file: $ENV_FILE"

if [[ "$PERSIST_ZSHRC" -eq 1 ]]; then
  remove_managed_block "$ZSHRC_FILE"
  {
    echo
    echo "$START_MARK"
    echo "source \"$ENV_FILE\""
    echo "$END_MARK"
  } >> "$ZSHRC_FILE"
  echo "[ok] updated ~/.zshrc with managed source block"
fi

echo
echo "[next] run:"
echo "       source \"$ENV_FILE\""
echo "       openclaw gateway restart"
echo "       openclaw channels status"
echo "       openclaw agents list --bindings"
echo
echo "[done] Per-agent Feishu setup finished."
